kind: environment
apiVersion: api.ibm.com/v1
metadata:
  name: Default_Environment_APIKey
  namespace: wM_APIKey_Weather
  version: "1.0"
  tags:
    - environment
spec:
  variables:
    - key: apikey_APIKey
      isSecret: false
      value: 758927ba80d9961789cc5c7fff9c311c
    - key: clientSecret_wMAPIKey
      isSecret: false
      value: b302d89fda74ad3c92bbc130925c3baf
