kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: Swagger_Petstore___OpenAPI_3_0
  namespace: vcc_nov28
  version: 1.0.27
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./Swagger_Petstore___OpenAPI_3_0-spec.json
  policy-sequence:
    - $ref: vcc_nov28:DPPolicy:1.0
