kind: environment
apiVersion: api.ibm.com/v1
metadata:
  name: Default_Environment_wM
  namespace: wM_Product_Weather
  version: "1.0"
  tags:
    - environment
spec:
  variables:
    - key: apikey_wM
      isSecret: true
      value: $(apikey_wM)
    - key: X-IBM-Client-Secret_wM_Product
      isSecret: true
      value: $(X-IBM-Client-Secret_wM_Product)
