kind: environment
apiVersion: api.ibm.com/v1
metadata:
  name: Default_Environment_NoAuth
  version: "1.0"
  namespace: wM_NoAuth_Weather
  tags: []
spec:
  variables:
    - key: x-gateway-apikey
      isSecret: true
      value: $(x-gateway-apikey)
    - key: X-IBM-Client-Id
      value: $(X-IBM-Client-Id)
      isSecret: true
